import Head from 'next/head'

import Header from '../components/Header';
import Cards from '../components/Cards';
import Recent from '../components/Recent';

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Strxangxl</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.sec}>
        <Header />
        <Cards />
        <Recent />
        <footer className={styles.footer}>
          <p className={styles.para}>Made By - strxangxl#9242(developer)</p>
        </footer>
      </div>
    </div>
  )
}
